package domain;
// Generated May 18, 2021 1:08:48 PM by Hibernate Tools 4.3.1

/**
 * Sinhvien generated by hbm2java
 */
public class Sinhvien implements java.io.Serializable {

    private Integer ma;
    private String ten;
    private String lop;
    private boolean phai;
    private double diem;

    public Sinhvien() {
    }

    public Sinhvien(String ten, String lop, boolean phai, double diem) {
        this.ten = ten;
        this.lop = lop;
        this.phai = phai;
        this.diem = diem;
    }

    public Integer getMa() {
        return this.ma;
    }

    public void setMa(Integer ma) {
        this.ma = ma;
    }

    public String getTen() {
        return this.ten;
    }

    public void setTen(String ten) {
        this.ten = ten;
    }

    public String getLop() {
        return this.lop;
    }

    public void setLop(String lop) {
        this.lop = lop;
    }

    public boolean isPhai() {
        return this.phai;
    }

    public String getSPhai() {
        return this.phai ? "Nam" : "Nu";
    }

    public void setPhai(boolean phai) {
        this.phai = phai;
    }

    public double getDiem() {
        return this.diem;
    }

    public void setDiem(double diem) {
        this.diem = diem;
    }

    @Override
    public String toString() {
        return "Sinhvien{" + "ma=" + ma + ", ten=" + ten + ", lop=" + lop + ", phai=" + phai + ", diem=" + diem + '}';
    }

}
