
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author anvin
 */
public class FrmQLSV extends javax.swing.JFrame {

    ArrayList<Lop> dsLop = null;
    DefaultListModel<Lop> modelLop = null;
    DefaultTableModel modelSV = null;
    Lop lopChon = null;
    SinhVien svChon = null;

    /**
     * Creates new form FrmQLSV
     */
    public FrmQLSV() {
        initComponents();
        dsLop = new ArrayList<>();
        for (int i = 1; i <= 14; i++) {
            Lop lop = new Lop("D18_TH" + i);
            lop.themSV(new SinhVien(i * 10 + 1, "Ti" + i, true));
            lop.themSV(new SinhVien(i * 10 + 2, "Suu" + i, true));
            dsLop.add(lop);
        }

        modelLop = (DefaultListModel<Lop>) lstLop.getModel();
        modelSV = (DefaultTableModel) tblSV.getModel();

        chuyenDsLopSangModel();
    }

    private void chuyenDsLopSangModel() {
        modelLop.clear();
        for (Lop lop : dsLop) {
            modelLop.addElement(lop);
        }
    }

    private void chuyenDsSVSangModel(Lop lop) {
        modelSV.setRowCount(0);
        if (lop != null) {
            for (SinhVien sv : lop.getDsSV()) {
                modelSV.addRow(
                        new Object[]{
                            sv.getMsv(),
                            sv.getTen(),
                            sv.getPhai()
                        }
                );
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupPhai = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLop = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        txtMSV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        radNam = new javax.swing.JRadioButton();
        radNu = new javax.swing.JRadioButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSV = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("LỚP");

        lstLop.setModel(new DefaultListModel<Lop>());
        lstLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lstLopMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(lstLop);

        jLabel3.setText("MSV:");

        jLabel4.setText("TÊN: ");

        jLabel5.setText("PHÁI: ");

        groupPhai.add(radNam);
        radNam.setSelected(true);
        radNam.setText("Nam");

        groupPhai.add(radNu);
        radNu.setText("Nữ");

        btnCapNhat.setText("CẬP NHẬT");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        tblSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSV", "TÊN", "PHÁI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblSVMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblSV);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMSV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTen))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radNam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radNu))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCapNhat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnThem))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtMSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(radNam)
                            .addComponent(radNu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCapNhat)
                            .addComponent(btnXoa)
                            .addComponent(btnThem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstLopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstLopMouseReleased
        int index = lstLop.getSelectedIndex();
        if (index >= 0) {
            lopChon = dsLop.get(index);
            chuyenDsSVSangModel(lopChon);
        } else {
            lopChon = null;
            chuyenDsSVSangModel(lopChon);
        }
        svChon = null;
        txtMSV.setText("");
        txtTen.setText("");
        radNam.setSelected(true);
        txtMSV.requestFocus();
    }//GEN-LAST:event_lstLopMouseReleased

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (lopChon != null) {
            int msv = Integer.parseInt(txtMSV.getText());
            String ten = txtTen.getText();
            boolean phai = radNam.isSelected();
            SinhVien sv = new SinhVien(msv, ten, phai);
            lopChon.themSV(sv);
            chuyenDsSVSangModel(lopChon);
            txtMSV.setText("");
            txtTen.setText("");
            radNam.setSelected(true);
            txtMSV.requestFocus();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblSVMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSVMouseReleased
        int index = tblSV.getSelectedRow();
        if (index >= 0) {
            svChon = lopChon.laySV(index);
            txtMSV.setText(svChon.getMsv() + "");
            txtTen.setText(svChon.getTen());
            if (svChon.isPhai()) {
                radNam.setSelected(true);
            } else {
                radNu.setSelected(true);
            }
        } else {
            svChon = null;
            txtMSV.setText("");
            txtTen.setText("");
            radNam.setSelected(true);
            txtMSV.requestFocus();
        }
    }//GEN-LAST:event_tblSVMouseReleased

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        if (svChon != null) {
            int msv = Integer.parseInt(txtMSV.getText());
            String ten = txtTen.getText();
            boolean phai = radNam.isSelected();
            svChon.setMsv(msv);
            svChon.setTen(ten);
            svChon.setPhai(phai);
            chuyenDsSVSangModel(lopChon);
            txtMSV.setText("");
            txtTen.setText("");
            radNam.setSelected(true);
            txtMSV.requestFocus();
            svChon = null;
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (svChon != null) {
            lopChon.xoaSV(svChon);
            chuyenDsSVSangModel(lopChon);
            txtMSV.setText("");
            txtTen.setText("");
            radNam.setSelected(true);
            txtMSV.requestFocus();
            svChon = null;
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
  

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmQLSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup groupPhai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Lop> lstLop;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JRadioButton radNu;
    private javax.swing.JTable tblSV;
    private javax.swing.JTextField txtMSV;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
